function omega_b = computeBodyRates(in1,in2,psi,psi_dot,m_t,g)
%computeBodyRates
%    OMEGA_B = computeBodyRates(IN1,IN2,PSI,PSI_DOT,M_T,G)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    21-Mar-2026 18:05:03

p_dot_e1 = in1(1,:);
p_dot_e2 = in1(2,:);
p_dot_e3 = in1(3,:);
p_ddot_e1 = in2(1,:);
p_ddot_e2 = in2(2,:);
p_ddot_e3 = in2(3,:);
t2 = abs(p_dot_e1);
t3 = abs(p_dot_e2);
t4 = cos(psi);
t5 = sin(psi);
t6 = g.*m_t;
t7 = t2.^2;
t8 = t3.^2;
t9 = p_dot_e1.*t4;
t10 = p_dot_e2.*t4;
t11 = p_dot_e1.*t5;
t12 = p_dot_e2.*t5;
t13 = p_dot_e3+t6;
t14 = abs(t13);
t15 = -t11;
t16 = t13.^2;
t17 = t9.*1i;
t18 = t12.*1i;
t20 = t9+t12;
t19 = t14.^2;
t21 = t20.^2;
t22 = t10+t15;
t25 = t13+t17+t18;
t23 = t22.^2;
t24 = t7+t8+t19;
t26 = t16+t21;
t27 = abs(t25);
t28 = 1.0./t24;
t29 = 1.0./t26;
t30 = 1.0./sqrt(t24);
t32 = 1.0./t27;
t31 = t30.^3;
t33 = p_ddot_e1.*t4.*t13.*t29;
t34 = p_ddot_e2.*t5.*t13.*t29;
t35 = p_ddot_e3.*t20.*t29;
t36 = t23.*t28;
t40 = psi_dot.*t13.*t22.*t29;
t37 = -t35;
t38 = -t36;
t39 = t38+1.0;
t43 = t33+t34+t37+t40;
t41 = sqrt(t39);
t42 = 1.0./t41;
omega_b = [p_ddot_e1.*t42.*(t5.*t30+t2.*t22.*t31.*sign(p_dot_e1))-p_ddot_e2.*t42.*(t4.*t30-t3.*t22.*t31.*sign(p_dot_e2))-psi_dot.*t20.*t32+psi_dot.*t20.*t30.*t42+p_ddot_e3.*t14.*t22.*t31.*t42.*sign(t13);t41.*t43-psi_dot.*t13.*t22.*t30.*t32;t22.*t30.*t43+psi_dot.*t13.*t32.*t41];
end
